[build]
cmd = "go build -o ./tmp/main.exe ./cmd/server"
bin = "./tmp/main.exe"
include_ext = ["go", "tpl", "html", "css", "js"]
exclude_dir = ["vendor", "tmp"]

[config]
windows_shell = true

[color]
main = "yellow"
watcher = "cyan"
runner = "green"

[log]
time = true